# Generated by Django 5.1.6 on 2026-02-15 15:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title_ru", models.CharField(max_length=220)),
                ("title_en", models.CharField(blank=True, max_length=220)),
                ("summary_ru", models.TextField(blank=True)),
                ("summary_en", models.TextField(blank=True)),
                ("body_ru", models.TextField(blank=True)),
                ("body_en", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="articles/"),
                ),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="CatalogPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_ru", models.CharField(max_length=220)),
                ("title_en", models.CharField(blank=True, max_length=220)),
                ("description_ru", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hydraulic", "Hydraulic seals"),
                            ("pneumatic", "Pneumatic seals"),
                            ("rotary", "Rotary seals"),
                            ("oring", "O-rings"),
                            ("kits", "Seal kits"),
                            ("other", "Other"),
                        ],
                        default="hydraulic",
                        max_length=30,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=120)),
                ("file", models.FileField(upload_to="catalogs/pdfs/")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="catalogs/covers/"
                    ),
                ),
                ("published_at", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-published_at", "title_ru"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("about", "About"),
                            ("production", "Production"),
                            ("products", "Products"),
                            ("catalogs", "Catalogs"),
                            ("knowledge", "Knowledge"),
                            ("contacts", "Contacts"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=40,
                    ),
                ),
                ("title_ru", models.CharField(max_length=200)),
                ("title_en", models.CharField(blank=True, max_length=200)),
                ("meta_title_ru", models.CharField(blank=True, max_length=240)),
                ("meta_title_en", models.CharField(blank=True, max_length=240)),
                ("meta_desc_ru", models.CharField(blank=True, max_length=320)),
                ("meta_desc_en", models.CharField(blank=True, max_length=320)),
                ("hero_title_ru", models.CharField(blank=True, max_length=200)),
                ("hero_title_en", models.CharField(blank=True, max_length=200)),
                ("hero_subtitle_ru", models.TextField(blank=True)),
                ("hero_subtitle_en", models.TextField(blank=True)),
                ("body_ru", models.TextField(blank=True)),
                ("body_en", models.TextField(blank=True)),
                ("is_published", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org_name", models.CharField(default="WESTSEAL", max_length=200)),
                (
                    "org_legal",
                    models.CharField(
                        default="ИП Туманов Иван Сергеевич", max_length=200
                    ),
                ),
                ("phone", models.CharField(default="+79626849611", max_length=50)),
                (
                    "email",
                    models.EmailField(default="westseal@mail.ru", max_length=254),
                ),
                (
                    "address",
                    models.CharField(default="Арцеуловская аллея 15", max_length=255),
                ),
                (
                    "work_hours",
                    models.CharField(
                        blank=True, default="Пн–Пт 9:00–18:00 (МСК)", max_length=120
                    ),
                ),
                (
                    "hero_badge_ru",
                    models.CharField(
                        blank=True,
                        default="Изготовление и поставка уплотнений",
                        max_length=120,
                    ),
                ),
                (
                    "hero_badge_en",
                    models.CharField(
                        blank=True,
                        default="Manufacture & supply of seals",
                        max_length=120,
                    ),
                ),
                (
                    "hero_cta_text_ru",
                    models.CharField(
                        blank=True, default="Отправить заявку", max_length=120
                    ),
                ),
                (
                    "hero_cta_text_en",
                    models.CharField(
                        blank=True, default="Send a request", max_length=120
                    ),
                ),
                (
                    "hero_cta_url",
                    models.CharField(
                        blank=True, default="/support/requests/new/", max_length=200
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="site/logo/"),
                ),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="site/hero/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=80)),
                ("title_ru", models.CharField(blank=True, max_length=200)),
                ("title_en", models.CharField(blank=True, max_length=200)),
                ("content_ru", models.TextField(blank=True)),
                ("content_en", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="pages/sections/"
                    ),
                ),
                ("cta_text_ru", models.CharField(blank=True, max_length=120)),
                ("cta_text_en", models.CharField(blank=True, max_length=120)),
                ("cta_url", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="core.page",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
