# Generated by Django 5.1.6 on 2026-02-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_ru", models.CharField(max_length=220)),
                ("title_en", models.CharField(blank=True, max_length=220)),
                ("task_ru", models.TextField(blank=True)),
                ("task_en", models.TextField(blank=True)),
                ("result_ru", models.TextField(blank=True)),
                ("result_en", models.TextField(blank=True)),
                ("lead_time", models.CharField(blank=True, max_length=120)),
                ("image", models.ImageField(blank=True, null=True, upload_to="cases/")),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="FAQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_ru", models.CharField(max_length=260)),
                ("question_en", models.CharField(blank=True, max_length=260)),
                ("answer_ru", models.TextField()),
                ("answer_en", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("text_ru", models.TextField()),
                ("text_en", models.TextField(blank=True)),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
