# Generated by Django 5.1.6 on 2026-02-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sealcategory_sealproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="sealcategory",
            name="name_en",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="sealproduct",
            name="name_en",
            field=models.CharField(blank=True, max_length=260),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="address_en",
            field=models.CharField(
                blank=True, default="Artseulovsky alley 15", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="org_legal_en",
            field=models.CharField(
                blank=True, default="IE Tumanov Ivan Sergeyevich", max_length=200
            ),
        ),
    ]
