# Generated by Django 5.1.6 on 2026-02-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_en_fields_to_sitesettings_and_catalog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="work_hours",
            field=models.CharField(
                blank=True, default="Пн–Пт 9:00–22:00 (МСК)", max_length=120
            ),
        ),
    ]
