# Generated by Django 5.1.6 on 2026-02-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_sitesettings_work_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogpdf",
            name="manufacturer_website",
            field=models.URLField(
                blank=True, max_length=300, verbose_name="Сайт производителя"
            ),
        ),
    ]
