# Generated by Django 5.1.6 on 2026-02-16 09:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0003_requestattachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("analogue", "Подбор аналога"),
                            ("manufacture", "Изготовление"),
                            ("supply", "Поставка"),
                        ],
                        default="analogue",
                        max_length=30,
                    ),
                ),
                ("dimensions", models.CharField(blank=True, max_length=200)),
                ("details", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="leads/files/"),
                ),
                ("source_page", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupportChatAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="chat/attachments/")),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="support.supportchatmessage",
                    ),
                ),
            ],
        ),
    ]
