# Generated by Django 5.1.6 on 2026-02-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0006_chat_admin_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportchatthread",
            name="admin_tg_message_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="Telegram message_id последнего форварда боту (для reply-роутинга)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supportchatmessage",
            name="via",
            field=models.CharField(default="site", max_length=20),
        ),
    ]
