# Generated by Django 5.1.6 on 2026-02-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0007_admin_tg_message_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supportchatthread",
            name="admin_tg_message_id",
        ),
        migrations.AddField(
            model_name="supportchatmessage",
            name="admin_tg_message_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Telegram message_id форварда администратору (для reply-роутинга)",
                null=True,
            ),
        ),
    ]
