# Generated by Django 5.1.6 on 2026-02-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0008_message_tg_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quicklead",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Быстрая заявка",
                "verbose_name_plural": "Быстрые заявки",
            },
        ),
        migrations.AlterModelOptions(
            name="requestattachment",
            options={
                "verbose_name": "Вложение заявки",
                "verbose_name_plural": "Вложения заявок",
            },
        ),
        migrations.AlterModelOptions(
            name="requestmessage",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Сообщение заявки",
                "verbose_name_plural": "Сообщения заявок",
            },
        ),
        migrations.AlterModelOptions(
            name="requestthread",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
        migrations.AlterModelOptions(
            name="supportchatattachment",
            options={
                "verbose_name": "Вложение чата",
                "verbose_name_plural": "Вложения чатов",
            },
        ),
        migrations.AlterModelOptions(
            name="supportchatmessage",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Сообщение чата",
                "verbose_name_plural": "Сообщения чатов",
            },
        ),
        migrations.AlterModelOptions(
            name="supportchatthread",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Чат поддержки",
                "verbose_name_plural": "Чаты поддержки",
            },
        ),
        migrations.AlterField(
            model_name="requestthread",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Новая"),
                    ("review", "Прочитана"),
                    ("in_work", "В работе"),
                    ("payment", "На оплате"),
                    ("paid", "Оплачено"),
                    ("in_transit", "В пути"),
                    ("answered", "Поступил ответ"),
                    ("closed_success", "Закрыта успешно"),
                    ("closed_fail", "Закрыто неуспешно"),
                    ("closed", "Закрыто"),
                ],
                default="sent",
                max_length=20,
            ),
        ),
    ]
