# Generated by Django 5.1.6 on 2026-02-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0009_extend_request_status_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportchatmessage",
            name="is_admin_seen",
            field=models.BooleanField(
                default=False, help_text="Сообщение просмотрено администратором."
            ),
        ),
    ]
